import os
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, func, Text
from sqlalchemy.orm import declarative_base, sessionmaker

# --- Configuration ---
# Get DB credentials from standardized DB_* environment variables
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASSWORD = os.getenv("DB_PASSWORD", "mlops_password")
DB_NAME = os.getenv("DB_NAME", "vigil_db")
DB_HOST = os.getenv("DB_HOST", "db")  # 'db' is the service name in docker-compose
DB_PORT = os.getenv("DB_PORT", "5432")

# PostgreSQL connection URL
SQLALCHEMY_DATABASE_URL = (
    f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# SQLAlchemy setup
# Note: FastAPI recommends async database access, but for simplicity in this template,
# we are using synchronous connection with a thread pool.
engine = create_engine(SQLALCHEMY_DATABASE_URL, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# --- Data Models ---

class PredictionLog(Base):
    """
    Table to log every production prediction made by the model API.
    """
    __tablename__ = "prediction_logs"

    id = Column(Integer, primary_key=True, index=True)
    
    # Input features
    feature_1 = Column(Float, nullable=False)
    feature_2 = Column(Float, nullable=False)
    
    # Model output
    prediction = Column(Integer, nullable=False)
    
    # Actual observed outcome (ground truth) - will often be Null initially
    target = Column(Integer, nullable=True) 
    
    # Metadata
    prediction_time = Column(DateTime, default=func.now())
    model_version = Column(String(50), default="v1.0")

class MonitoringMetric(Base):
    """
    Table to store the summary metrics and drift scores generated by the 
    monitoring job.
    """
    __tablename__ = "monitoring_metrics"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=func.now())
    data_drift_score = Column(Float, nullable=False)
    num_drifted_features = Column(Integer, nullable=False)
    metric_name = Column(String(100), nullable=False)
    metric_value = Column(Float, nullable=False)
    report_summary = Column(Text, nullable=True) 
    model_version = Column(String(50), nullable=False)
    batch_start_time = Column(DateTime, nullable=False)
    batch_end_time = Column(DateTime, nullable=False)

def get_db():
    """Dependency function to get a database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
